# Generated by Django 5.0.6 on 2024-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.CharField(default='Unknown Hospital', max_length=255),
        ),
        migrations.AddField(
            model_name='donor',
            name='hospital',
            field=models.CharField(default='Unknown Hospital', max_length=255),
        ),
    ]
